name: gg_time_controller
description: A time controller for media players with play, pause, stop, jumpTo and animateTo methods.
version: 1.0.1
homepage: https://github.com/inlavigo/gg_time_controller

environment:
  sdk: ">=3.2.0 <4.0.0"

dependencies:
  fake_async: ^1.3.1
  gg_periodic_timer: ^1.0.0+beta.1
  gg_typedefs: ^1.0.0+beta.4
  gg_value: ^1.3.6+4
  meta: ^1.8.0

dev_dependencies:
  args: ^2.4.2
  gg_capture_print: ^1.0.2
  gg_install_gg: ^1.0.1
  lints: ^3.0.0
  pana: ^0.22.2
  test: ^1.16.0
