name: gg_time_controller
description: A time controller for media players with play, pause, stop, jumpTo and animateTo methods.
version: 1.0.0+beta.9
homepage: https://github.com/inlavigo/gg_time_controller

environment:
  sdk: ">=2.18.0 <3.0.0"

dependencies:
  fake_async: ^1.3.1
  gg_periodic_timer: ^1.0.0+beta.1
  gg_typedefs: ^1.0.0+beta.4
  gg_value: ^1.3.6+4
  meta: ^1.8.0

dev_dependencies:
  lints: ^2.0.0
  test: ^1.16.0
  flutter_lints: ^2.0.1
